# .github/workflows/cr.yml 파일 생성
 
name: Code Review
 
permissions:
  contents: read
  pull-requests: write
 
on:
  pull_request:
    types: [opened, synchronize]

# 워크플로우에서 실행할 동작
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
